# SPDX-License-Identifier: GPL-3.0-or-later
"""Add independently recorded Thunder and complete prayer cinematic evidence."""
import argparse
import json
from pathlib import Path

import battle_semantic_coverage_ledger_dev16 as physical
from battle_action_catalog_qa import PIN, digest

ledger=physical.ledger
ledger.REPORTS += (
    ('research/redux-battle-thunder-coverage-dev16.json',
     'Complete prepared nonlethal Thunder hit loops; distinct actual PSI/non-PSI rows, random target/status filtering, selected shields and badge reflection. Outer AI/turn/PP payment and lethal continuation remain unevaluated.'),
)


def main():
    ledger.main()
    parser=argparse.ArgumentParser(add_help=False)
    parser.add_argument('--output',type=Path,required=True)
    parser.add_argument('--root',type=Path,default=Path(__file__).resolve().parent.parent)
    args,_=parser.parse_known_args()
    result=json.loads(args.output.read_text())
    path='research/redux-complete-prayer-cinematics-review.json'
    report_file=args.root/path
    report=json.loads(report_file.read_text())
    if not report['allPassed'] or report['sourceRevision']!=PIN:
        raise ValueError('Incomplete/unpinned prayer evidence')
    profile=next(p for p in report['profiles'] if p['profile']=='Redux')
    if profile['packSha256']!=result['assetsSha256'] or not profile['allPassed']:
        raise ValueError('Prayer evidence has a different pack or failed cases')
    covered={row['function']:row for row in result['covered']}
    for row in profile['cases']:
        if not row['passed'] or row['callback'] not in covered:
            raise ValueError('Prayer evidence must add branches to already inventoried callbacks')
        covered[row['callback']]['evidence'].append({
            'report':path,'profile':'Redux','selectedPassedCases':1,'entryPcCases':{'0':1},
            'scope':'Complete prepared prayer callback entry, actual source scene actors/scripts and natural wait signals through cinematic, damage and battle-scene return. Entry flags372/651 are source prerequisites; flag522 is generated by real entity scripts. No complete final battle or physical-input proof.',
            'requiredSceneNpcs':row['requiredSceneNpcs'],'sourceWarp':row['sourceWarp']})
    result['reports'].append({'path':path,'sha256':digest(report_file),
        'runtimeSha256':profile['runtimeSha256'],
        'executedPlayerLibrarySha256':profile['privateBuild']['productionLibrarySha256'],
        'privateDriverSourceSha256':profile['privateBuild']['driverSourceSha256'],
        'recordedCases':len(profile['cases']),'activeCallbacksWithSelectedCases':len(profile['cases']),
        'scope':'Prepared complete prayer1–7 callback cinematics; same seven callback IDs as previous staged damage report.',
        'limits':report.get('limits',[])})
    result['limits'].append('Complete prayer cinematics use the separate dev15 v6 production library; its exact hashes remain separate from the v5 damage, physical and Thunder tests.')
    args.output.write_text(json.dumps(result,indent=2)+'\n',encoding='utf-8')
    print(json.dumps({'completePrayerCallbacksSupplemented':len(profile['cases']),
        'callbacksWithSelectedSemanticEvidence':result['callbacksWithSelectedSemanticEvidence'],
        'callbacksWithoutSelectedSemanticEvidence':result['callbacksWithoutSelectedSemanticEvidence']}))


if __name__=='__main__':main()
